[package]
name = "bun_plugin"
version = "0.0.2"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.3"
proto_pdk = "0.2.1"
serde = "1.0.167"
