[package]
name = "bun_plugin"
version = "0.0.2"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.3"
proto_pdk = "0.2.3"
serde = "1.0.167"

[dev-dependencies]
proto_core = "0.12.2"
proto_pdk_test_utils = "0.1.3"
starbase_sandbox = "0.1.5"
tokio = "1.29.1"
