[package]
name = "bun_plugin"
version = "0.3.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.4"
proto_pdk = { version = "0.7.0" } #, path = "../../proto/crates/pdk" }
serde = "1.0.188"

[dev-dependencies]
proto_pdk_test_utils = { version = "0.6.1" } # , path = "../../proto/crates/pdk-test-utils" }
starbase_sandbox = "0.1.10"
tokio = "1.32.0"

[profile.release]
codegen-units = 1
lto = true
