[package]
name = "bun_plugin"
version = "0.0.3"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.3"
proto_pdk = "0.4.0"
serde = "1.0.183"

[dev-dependencies]
proto_pdk_test_utils = "0.3.0"
starbase_sandbox = "0.1.8"
tokio = "1.29.1"
