[package]
name = "bun_plugin"
version = "0.0.3"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ['cdylib']

[dependencies]
extism-pdk = "0.3.3"
proto_pdk = { version = "0.3.1", path = "../proto/crates/pdk" }
serde = "1.0.167"

[dev-dependencies]
# proto_core = "0.12.2"
proto_pdk_test_utils = { version = "0.2.1", path = "../proto/crates/pdk-test-utils" }
starbase_sandbox = "0.1.5"
tokio = "1.29.1"
